### ISSUE TITLE
txt 경로 오류

### ISSUE THREAD

**Issue by jingyeong27** [jingyeong27/Life_Alert_Bot#2]
기온별 옷차림 정보를 출력하기 위해 txt 파일을 사용하셨는데, 자신의 컴퓨터에서는 경로를 지정하여 txt를 연결했지만 다른 사람의 컴퓨터에서도 경로를 연결하여야 할텐데 그런 번거로움을 없애기 위해 코드를 수정할 방법은 없을까요?

2c51806eb19a835e111069ef08cda86997b60b3e

**Comment by mjkim0468** [comment]
제 컴퓨터뿐만 아니라 모든 사용자의 컴퓨터에서 '기온별 옷차림' 이 잘 작동하도록 절대 경로로 표시해놨던 텍스트 파일을 따로 작성하여 코드에 포함시킴으로써 파일 이름만으로도 실행 가능하게 해놓았습니다.
