### ISSUE TITLE
코로나 지침 업데이트

### ISSUE THREAD

**Issue by mjkim0468** [jingyeong27/Life_Alert_Bot#3]
코로나 지침이 텍스트 파일로 작성됐던데, 지침이 바뀔 때마다 자동으로 업데이트되는 건가요?

23e6ca5dad22feef58f75d104455520fb09231de

**Comment by jingyeong27** [comment]
네, 코로나 방역 지침이 바뀔 때마다 txt파일을 바꾸어 깃허브에 커밋할 계획입니다.
