### ISSUE TITLE
나의 날씨 elif절

### ISSUE THREAD

**Issue by mjkim0468** [jingyeong27/Life_Alert_Bot#4]
나의 날씨를 출력하는 elif 절에서 my_adr과 my_wea는 string처리를 하는데 my_tem은 text 처리를 하는 이유는 무엇인가요? 

7782c27198ef865a88603d88227240faf56a7a2d

**Comment by jingyeong27** [comment]
my_adr과 my_wea의 웹 사이트로 들어가 elements들을 살펴보면 파싱하게 되는 정보가 string으로 표현할 수 있는 반면 my_tem은 #text 메시지로 표현되어 있어 string으로 표현할 수 없습니다. 따라서 my_tem을 soup하는 과정에서 .text로 변환하여 데이터 값을 읽어와야 합니다.

**Comment by mjkim0468** [comment]
답변 감사합니다.
